#!/usr/bin/env python3

import os
import sys

if __name__ == '__main__':
    working_dir = os.path.abspath(os.path.dirname(__file__))
    # add project dir to your python path
    # I mean the directory which contains 'manage.py'
    sys.path.insert(0, os.path.abspath(os.path.join(working_dir, 'testproject')))

    # adding runstandalone to python path to make DjangoRunStandAlone importable
    sys.path.insert(0, os.path.abspath(os.path.join(working_dir + '/../')))

    print(sys.path)
    # import DjangoRunStandAlone
    import runstandalone.runstandalone
    dj_runner = runstandalone.runstandalone.DjangoRunStandAlone(
        wsgi='testproject.wsgi' # this is the wsgi.py in project. it should be importable
    )
    dj_runner.run()
