#!/usr/bin/env python3

import os
import sys

if __name__ == '__main__':
    # add project dir to your python path
    # I mean the directory which contains 'manage.py'
    sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + '/testproject'))

    # adding runstandalone to python path to make DjangoRunStandAlone importable
    sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + '/../'))

    # import DjangoRunStandAlone
    from runstandalone.runstandalone import DjangoRunStandAlone
    dj_runner = DjangoRunStandAlone(
        wsgi='testproject.wsgi' # this is the wsgi.py in project. it should be importable
    )
    dj_runner.run()
